name: development

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, development]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules in backend
        run: npm install
    
      - run: rm package-lock.json

      - run: cp .env.dev .env
      - run: pm2 start backend

      
